//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Losev326_ProizvodPrakt.Components.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.Perk = new HashSet<Perk>();
            this.Power = new HashSet<Power>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int MoveSpeedId { get; set; }
        public string TerrorRadius { get; set; }
        public string Description { get; set; }
        public string History { get; set; }
        public byte[] Image { get; set; }
        public int TypeCharacterId { get; set; }
        public int TypeArticleId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual MoveSpeed MoveSpeed { get; set; }
        public virtual TypeArticle TypeArticle { get; set; }
        public virtual TypeCharacter TypeCharacter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perk> Perk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Power> Power { get; set; }
    }
}
