//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Losev326_ProizvodPrakt.Components.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbdWikiEntities : DbContext
    {
        public DbdWikiEntities()
            : base("name=DbdWikiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<Map> Map { get; set; }
        public virtual DbSet<MoveSpeed> MoveSpeed { get; set; }
        public virtual DbSet<Perk> Perk { get; set; }
        public virtual DbSet<Power> Power { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeArticle> TypeArticle { get; set; }
        public virtual DbSet<TypeCharacter> TypeCharacter { get; set; }
        public virtual DbSet<TypePerk> TypePerk { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
